# Generated by Django 5.0.6 on 2026-07-05 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('membership_status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('suspended', 'معلق'), ('expired', 'منقضی شده')], default='active', max_length=10, verbose_name='وضعیت عضویت')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], default='beginner', max_length=15, verbose_name='سطح هنرجو')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='نام تماس اضطراری')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=11, verbose_name='شماره تماس اضطراری')),
                ('medical_notes', models.TextField(blank=True, verbose_name='یادداشت\u200cهای پزشکی')),
                ('joined_date', models.DateField(auto_now_add=True, verbose_name='تاریخ عضویت در باشگاه')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل هنرجو',
                'verbose_name_plural': 'پروفایل\u200cهای هنرجویان',
            },
        ),
    ]
