# Generated by Django 5.0.6 on 2026-07-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'پروفایل هنرجو', 'verbose_name_plural': 'پروفایل\u200cهای هنرجویان'},
        ),
    ]
