# Generated by Django 5.0.6 on 2026-07-05 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('name', models.CharField(choices=[('silk', 'سیلک (پارچه هوایی)'), ('hoop', 'هوپ (حلقه هوایی)'), ('sling', 'اسلینگ'), ('stretch', 'استرچ'), ('flexibility', 'انعطاف\u200cپذیری')], max_length=20, unique=True, verbose_name='نام رشته')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('icon', models.CharField(blank=True, help_text='کلاس آیکون Font Awesome', max_length=50, verbose_name='آیکون')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='disciplines/', verbose_name='تصویر کاور')),
            ],
            options={
                'verbose_name': 'رشته',
                'verbose_name_plural': 'رشته\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('title', models.CharField(max_length=150, verbose_name='نام کلاس')),
                ('level', models.CharField(choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], max_length=15, verbose_name='سطح')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='ظرفیت')),
                ('equipment_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تجهیزات')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت (تومان)')),
                ('session_date', models.DateField(verbose_name='تاریخ برگزاری')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='classes/', verbose_name='تصویر کلاس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coached_classes', to=settings.AUTH_USER_MODEL, verbose_name='مربی')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_sessions', to='classes.discipline', verbose_name='رشته')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
                'ordering': ['session_date', 'start_time'],
            },
        ),
    ]
