# Generated by Django 5.0.6 on 2026-07-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ['name'], 'verbose_name': 'رشته', 'verbose_name_plural': 'رشته\u200cها'},
        ),
    ]
