# Generated by Django 5.0.6 on 2026-07-05 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=11, verbose_name='شماره تماس')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('student_name', models.CharField(max_length=100, verbose_name='نام هنرجو')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='امتیاز (از ۵)')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
            ],
            options={
                'verbose_name': 'نظر هنرجو',
                'verbose_name_plural': 'نظرات هنرجویان',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='تصویر')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('discipline', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='classes.discipline', verbose_name='رشته مرتبط')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
                'ordering': ['-created_at'],
            },
        ),
    ]
