# Generated by Django 5.0.6 on 2026-07-05 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at'], 'verbose_name': 'نظر هنرجو', 'verbose_name_plural': 'نظرات هنرجویان'},
        ),
    ]
