# Generated by Django 5.0.6 on 2026-07-05 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تایید'), ('confirmed', 'تایید شده'), ('cancelled', 'لغو شده'), ('completed', 'برگزار شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ لغو')),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, verbose_name='دلیل لغو')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.classsession', verbose_name='کلاس')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='هنرجو')),
            ],
            options={
                'verbose_name': 'رزرو',
                'verbose_name_plural': 'رزروها',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'class_session')},
            },
        ),
    ]
